services:
  micro-sender:
    image: micro-sender
    container_name: 'micro-sender'
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
    ports:
      - 9000:9000
    networks:
      loki:
      sender:
        aliases:
          - "micro-sender"
  micro-recipient:
    image: micro-recipient
    container_name: 'micro-recipient'
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
    ports:
      - 9001:9001
    networks:
      loki:
      recipient:
        aliases:
          - "micro-recipient"
  micro-collector:
    image: micro-collector
    container_name: 'micro-collector'
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    logging:
      driver: loki
      options:
        loki-url: http://localhost:3100/loki/api/v1/push
    ports:
      - 9002:9002
    networks:
      loki:
      recipient:
        aliases:
          - "micro-collector"
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
      loki:
      sender:
        aliases:
          - "rabbit"
      recipient:
        aliases:
          - "rabbit"
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    networks:
      loki:
      sender:
        aliases:
          - "grafana"
      recipient:
        aliases:
          - "grafana"
  prometheus:
    image: prom/prometheus:v2.30.3
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
  loki:
    image: grafana/loki:2.2.1
    ports:
      - "3100:3100"
    volumes:
      - ./promtailloki/loki:/etc/loki
    command: -config.file=/etc/loki/loki-config.yaml
    networks:
      loki:

  promtail:
    image: grafana/promtail:2.2.1
    volumes:
      - /var/log:/var/log
      - ./promtailloki/promtail:/etc/promtail
    command: -config.file=/etc/promtail/promtail-config.yaml
    networks:
      loki:
volumes:
  prometheus-data:
  grafana-data:
    external: true
networks:
  loki:
  sender:
    driver: bridge
  recipient:
    driver: bridge
